### ISSUE TITLE
Repository 이름 바꾸기

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/pdf-cloud#1]
`pdf-cloud`라는 이름보다는 `examples-mirror`정도로 변경하는 것이 어떨까 합니다. 
원래 이 repository의 목적은, gshslatexintro 와 examples 의 용량을 최소화하고, 컴파일된 pdf 결과들 및 (용량이 큰 경우) 그림 파일들을 여기에 cloud처럼 대용량 repository에 몰아넣자는 취지였습니다. 하지만 현재 이 `pdf-cloud`가 `examples`에 대한 미러링만을 하고 `gshslatexintro`에 대해서는 하지 않는 것을 고려한다면, 현재 이름은 적절치 않아 보입니다. 
다시 pdf-cloud라는 이름의 repository를 만들지 않는 한, 원래 링크 사용해도 리다이렉트가 되기 때문에 이름을 변경해도 큰 부작용은 없을 것으로 보입니다. 이것에 관해서는 [Renaming a repository](https://help.github.com/articles/renaming-a-repository/)를 참조하십시오.

이 안에 대한 회원분들의 의견을 묻고, 변경할 repository의 이름 또한 공모하려 합니다. (새 이름의 경우 별다른 의견이 없으시다면 `examples-mirror`를 사용할 예정입니다.) 특히 @evenharder 님과 @LeeJuchan 님께서는 어떻게 생각하시는가요?

**Comment by LeeJuchan** [comment]
Repository 이름에 대하여는 크게 중요치 않다고 생각하여, 변경하는 것에 반대하지 않습니다.
제가 `pdf-cloud`에 크게 관여한 적이 없어, repository 성격을 잘 알지 못하기에 새 이름에 관한 의견은 딱히 없습니다.

**Comment by seungwonpark** [comment]
@LeeJuchan 네... `pdf-cloud`의 이름을 `examples-mirror`로 변경하려 하는 이유는, `pdf-cloud`라는 이름만으로는 이 repository의 성격을 알기가 힘들기 때문입니다. Repository마다 있는 description과 `README.md`, [gshslatexintro/gshslatexintro Wiki](https://github.com/gshslatexintro/gshslatexintro/wiki/경기과학고-텍-사용자협회-규범집#repository별-설명)에 설명을 해놓았었는데, 회원 분들께서도 잘 모르고 계셨다고 하니 repository의 이름이 얼마나 중요한 역할을 하는지 새삼 깨닫게 되는군요 ㅠㅠ 피드백 감사합니다.

`pdf-cloud`의 본래 목적은 다른 repository들의 용량을 최소화하는 데에 있었습니다. 컴파일된 pdf 파일들이나 대용량 이미지/동영상 등을 `pdf-cloud`에 몰아넣는 것이지요. 그런데 지난 1년간 새로운 회원 분들께서 공헌해주시던 때를 보면, 따로 `pdf-cloud`에 pdf 파일들을 옮겨놓는 경우가 적어서, 대부분 제가 따로 `pdf-cloud`에 파일을 옮기는 작업을 자주 하고는 했습니다. 

이것은 우리 협회에 공헌할 때 어떻게 해야 하는지, 관련 지침을 제대로 알리지 않은 저의 탓입니다.

repository 이름을 바꾸는 것에 대한 이의/추가의견이 일주일 내로 없다면, 기존에 `pdf-cloud`가 하던 역할을 `examples-mirror` 및 `gshslatexintro-mirror`로 옮기도록 하겠습니다. `examples-mirror`는 `pdf-cloud`에서 이름만 바꿔서 만들고, `gshslatexintro-mirror`는 repository를 새로 생성할 계획입니다. 또한, 빠른 시일 내에 협회 공헌 지침 안내문서를 만들어 `An-Introduction-to-LaTeX`에 탑재하도록 하겠습니다.

**Comment by seungwonpark** [comment]
우선 repository 명칭 변경은 완료하였으니, 이 issue는 닫도록 하겠습니다.
