### ISSUE TITLE
결과 파일에 그림과 레퍼런스 번호가 깨졌어요ㅠㅠㅠ

### ISSUE THREAD

**Issue by Kim-kyeongtae** [gshslatexintro/pdf-cloud#3]

**Comment by seungwonpark** [comment]
어느 파일을 말씀하시는 것인가요?

**Comment by Kim-kyeongtae** [comment]
pdf 파일이요.

**Comment by seungwonpark** [comment]
모든 pdf 파일이 그렇다는 건가요? 아니면 어느 특정 파일이 그렇다는 건가요?
설명을 명확히 해 주시면 감사하겠습니다.

**Comment by Kim-kyeongtae** [comment]
Advanced_Physics_14041에 있는 파일입니다. 지금 보니까 이 issue가 gshslatexintro/examples-mirror 전체에 걸려 있네요ㅠㅠ

**Comment by seungwonpark** [comment]
그렇네요. 지적 감사합니다.
examples-mirror에는 사용한 그림 파일도 전부 첨부했어야 했는데 누락되었군요. 이를 수정하는 Pull request를 곧 넣겠습니다.
